---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - tar
- name: download geth
  shell: "wget -qO- {{ geth_url }}/{{ geth_version }}.tar.gz | tar xvz -C {{ geth_dir }}"
  args:
    creates: "{{ geth_dir }}/{{ geth_version }}"
- name: setup unit service
  template:
    src: templates/service.jinja2
    dest: "/etc/systemd/system/{{ geth_name }}.service"
  notify:
    - restart application service
- name: start unit service
  systemd:
    name: "{{ geth_name }}"
    state: started
    enabled: yes
